title: Chali Andrew
logo: /assets/img/profile.jpeg
description: Passionate Frontend Developer with expertise in React, JavaScript (ES6+), TypeScript, and modern CSS frameworks,
I specialize in crafting high-performance, responsive, and user-friendly web applications with a focus on clean code, accessibility (a11y), and seamless UX.
# show_downloads: false
theme: jekyll-theme-minimal
